---
title: "Data_analysis"
author: "Yuting Lang"
date: "2022-10-14"
output: pdf_document
---
```{r}
library(ggplot2)
```

```{r}
results <- read.csv("Output.csv")
results[, "Strategy"] <- as.factor(results[, "Strategy"])
results[, "Placed.on.Edges"] <- as.factor(results[, "Placed.on.Edges"])
results[, "Extinguish.Ratio"] <- round(results[, "Truck.Extinguish"]/
                (results[, "Self.Extinguish"] + results[, "Truck.Extinguish"]), 4)


summary(results[, 1:5])
dim(results)
```



```{r}
# Simple model without interaction terms (not used in analysis)
model.1 <- lm(Extinguish.Ratio~Strategy + Number.of.Truck + Max.speed + Vision
               + Placed.on.Edges, data = results)
summary(model.1)
```

```{r}
# Full model (used in analysis)
model.2 <- lm(Extinguish.Ratio~(Strategy + Number.of.Truck + Max.speed + Vision
               + Placed.on.Edges)^2, data = results)
summary(model.2)
```

```{r}
# Apply step function to eliminate variables in full model
step(model.2)
```

```{r}
# Final model for analysis
model.3 <- lm(Extinguish.Ratio ~ Strategy + Number.of.Truck + 
    Max.speed + Vision + Placed.on.Edges + Strategy:Number.of.Truck + 
    Number.of.Truck:Max.speed + Number.of.Truck:Placed.on.Edges, 
    data = results)

summary(model.3)
```



```{r}
# Overview for some variables
par(mfrow = c(2, 3))
plot(Extinguish.Ratio~Strategy, data = results,  names = c("Biggest", "Closest", "Parallel "))
plot(Extinguish.Ratio~Placed.on.Edges, data = results)
```

The following plots are for significant variables in the final model:
```{r warning = FALSE}
ggplot(data = results, aes(Number.of.Truck, Extinguish.Ratio, col = Strategy)) +
  geom_point() +
  geom_smooth()
```

```{r warning = FALSE}
library(tidyverse)
ggplot(data = results, aes(Max.speed, Extinguish.Ratio, col = Strategy)) +
  geom_point(aes(col = Strategy)) +
  geom_smooth()
```

```{r}
ggplot(data = results, aes(Number.of.Truck, Extinguish.Ratio, col = Placed.on.Edges)) +
  geom_point(aes(col = Placed.on.Edges)) +
  geom_smooth()
```
